# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'housesigma' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for housesigma
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path
                
  pod 'GoogleMaps'
end
